#!/usr/bin/env zsh

# jump between words instead of WORDS
autoload -U select-word-style
select-word-style bash

# The following lines were added by compinstall
zstyle ':completion:*' completer _expand _complete _match _approximate _prefix
zstyle ':completion:*' completions 1
zstyle ':completion:*' glob 1
zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' match-original both
zstyle ':completion:*' matcher-list '' 'r:|[._-]=** r:|=**' 'l:|=* r:|=*'
zstyle ':completion:*' max-errors 3
zstyle ':completion:*' menu select=2
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/Users/wvega/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

export HISTSIZE=10000 # set history size
export SAVEHIST=10000 # save history after logout

setopt INC_APPEND_HISTORY
setopt HIST_IGNORE_DUPS   # do not add an entry if it's a duplicate of the previous entry
setopt EXTENDED_HISTORY   # add timestamp for each entry

source "${HOME}/.myzsh/alias.zsh"

source "${HOME}/.myzsh/lang.zsh"

source "${HOME}/.myzsh/plugins.zsh"

# load environment variables with secrets
source "${HOME}/.myzsh/secrets.zsh"

# load snippets that modify $PATH last
source "${HOME}/.myzsh/path.zsh"

# load rbenv
eval "$(rbenv init -)"

# load pyenv
eval "$(pyenv init -)"

# load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh" --no-use  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#### Direnv hooks ####
eval "$(direnv hook zsh)"
#### END Direnv hooks ###
