#!/bin/bash
# vim: set syntax=bash

if [[ ! -e "/usr/local/bin/brew" ]]; then
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
fi

brew bundle check --file="$1" >/dev/null 2>&1  || {
    brew bundle --file="$1"
}
