#!/bin/bash
# vim: set syntax=bash

if [[ ! -e "/usr/local/bin/brew" ]]; then
	echo "Installing Homebrew"
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

echo "Checking and installing Homebrew bundle"

brew bundle check --quiet --file="$1"

if [[ ! $? -eq 0 ]]; then
	echo "Installing missing dependencies"
	brew bundle --file="$1"
fi
