#!/bin/bash
# vim: set syntax=bash

if [[ ! -e "/usr/local/bin/brew" ]]; then
	echo "Installing Homebrew"
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew bundle check --file="$1" >/dev/null 2>&1  || {
    brew bundle --file="$1"
}
